############################################################
#
# web访问端口号
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
  servlet:
    context-path: /foodie

############################################################
#
# 选择生效配置文件
#
############################################################
spring:
  banner:
    location: myBanner.txt
  profiles:
    active: dev









